#!/usr/bin/env python3
"""
Master Preprocessing Pipeline
==============================

Orchestrates the full preprocessing workflow:
  1. Prepare clean paired data (from raw input CSV)
  2. Create physics-informed 3-cluster assignments
  3. Generate ready-to-train datasets

Usage:
  python run_preprocessing_pipeline.py                    # Uses default paths
  python run_preprocessing_pipeline.py --input-csv PATH   # Custom input
  python run_preprocessing_pipeline.py --skip-cluster     # Skip clustering phase
"""

import sys
import argparse
from pathlib import Path
import logging

# Add parent dir to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from prepare_gnn_data_clean import CleanGNNDataPreparator
from create_physics_clusters import PhysicsFeatureClusterer


def setup_logging():
    """Configure logging."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    return logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(
        description='Run full preprocessing pipeline from raw data to clustered datasets'
    )
    parser.add_argument(
        '--input-csv',
        default='../data/step3_with_injection_labels.csv',
        help='Input CSV path (default: ../data/step3_with_injection_labels.csv) - generated by earlier steps'
    )
    parser.add_argument(
        '--skip-cluster',
        action='store_true',
        help='Skip clustering phase (only do data preparation)'
    )
    parser.add_argument(
        '--output-dir',
        default='./data',
        help='Output directory for preprocessed data (default: ./data)'
    )
    
    args = parser.parse_args()
    
    logger = setup_logging()
    
    print("\n" + "=" * 80)
    print("STOCHASTIC ML SPRAY - PREPROCESSING PIPELINE")
    print("=" * 80)
    print(f"\nPhase 1: Data Preparation (Clean - no disappearing particles)")
    print(f"Phase 2: Physics-Informed Clustering (3 clusters)")
    print()
    
    output_dir = Path(args.output_dir)
    
    try:
        # =====================================================================
        # PHASE 1: Data Preparation
        # =====================================================================
        print("\n" + "-" * 80)
        print("PHASE 1: DATA PREPARATION")
        print("-" * 80)
        
        preparator = CleanGNNDataPreparator(
            input_csv=args.input_csv,
            output_dir=str(output_dir)
        )
        
        train_df, val_df, test_df, metadata = preparator.prepare()
        
        print("\n✓ Phase 1 complete!")
        print(f"  Prepared data saved to: {output_dir}")
        
        # =====================================================================
        # PHASE 2: Physics-Informed Clustering (Optional)
        # =====================================================================
        if not args.skip_cluster:
            print("\n" + "-" * 80)
            print("PHASE 2: PHYSICS-INFORMED CLUSTERING")
            print("-" * 80)
            
            clusterer = PhysicsFeatureClusterer(
                train_csv=str(output_dir / 'train_paired.csv'),
                val_csv=str(output_dir / 'val_paired.csv'),
                test_csv=str(output_dir / 'test_paired.csv'),
                metadata_pkl=str(output_dir / 'metadata.pkl'),
                output_dir=str(output_dir),
                n_clusters=3
            )
            
            train_df, val_df, test_df = clusterer.cluster()
            
            print("\n✓ Phase 2 complete!")
            print(f"  Clustered data saved to: {output_dir}")
        else:
            print("\n(Clustering phase skipped)")
        
        # =====================================================================
        # Summary
        # =====================================================================
        print("\n" + "=" * 80)
        print("PREPROCESSING PIPELINE - COMPLETE")
        print("=" * 80)
        print(f"\nOutput Directory: {output_dir}")
        print("\nGenerated Files:")
        print(f"  • train_paired.csv       ({len(train_df):,} samples)")
        print(f"  • val_paired.csv         ({len(val_df):,} samples)")
        print(f"  • test_paired.csv        ({len(test_df):,} samples)")
        
        if (output_dir / 'gmm_model.pkl').exists():
            print(f"  • gmm_model.pkl          (3-cluster GMM model)")
        
        print(f"  • metadata.pkl           (feature names, scalers, metadata)")
        
        print("\n✓ Data is ready for model training!")
        print("=" * 80 + "\n")
        
    except Exception as e:
        logger.error(f"Pipeline failed: {e}", exc_info=True)
        sys.exit(1)


if __name__ == '__main__':
    main()
